
const x = 10

try {
    x=2
} catch (error) {
    console.log(`error ${error}`)
}

console.log('fluxo normal')




